version: "3.8"

services:
  mysql:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "cathunter"
    ports:
      - "3307:3306"
    volumes:
      - "./.db:/var/lib/mysql"
